imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

twig:
    form:
        resources:
            - 'AcmeBillerBundle::fields.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        memory:   true
        dbname:   'temp.db'
        user:     %database_user%
        password: %database_password%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

services:
    infinite_form.polycollection_type:
        class: Acme\BillerBundle\Form\Type\PolyCollectionType
        tags:
            form_type:
                name: form.type
                alias: polycollection